# Job Market Intelligence 2026

## Objective
Analyze job postings to identify:
- Most demanded technical skills
- Job locations
- Salary trends
- Experience requirements
- Work modes
- Skill combinations
- Job opportunities for freshers

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

print("Libraries imported successfully!")

Libraries imported successfully!

In [2]:
from pathlib import Path

data_folder = Path("../data/raw")

csv_files = list(data_folder.glob("*.csv"))

print(f"Number of CSV files: {len(csv_files)}")

for file in csv_files:
    print(file.name)

Number of CSV files: 3
skills_rows.csv
vacancies_rows.csv
vacancy_skills_rows.csv

In [3]:
for file in csv_files:

    df = pd.read_csv(file)

    print("=" * 80)
    print(f"FILE: {file.name}")
    print(f"Rows: {df.shape[0]}")
    print(f"Columns: {df.shape[1]}")

    print("\nColumn Names:")
    print(df.columns.tolist())

    print("\nFirst 5 Rows:")
    display(df.head())

    print("\nMissing Values:")
    display(df.isnull().sum())

================================================================================
FILE: skills_rows.csv
Rows: 2033
Columns: 3

Column Names:
['id', 'created_at', 'name']

First 5 Rows:

   id                     created_at            name
0   1  2026-03-19 11:24:51.895497+00             SQL
1   2  2026-03-19 11:24:51.909554+00           Agile
2   3  2026-03-19 11:24:51.948616+00     ERP Systems
3   4  2026-03-19 11:24:51.987942+00  Issue Tracking
4   5  2026-03-19 11:24:52.016191+00       Snowflake

Missing Values:

id            0
created_at    0
name          0
dtype: int64

================================================================================
FILE: vacancies_rows.csv
Rows: 2154
Columns: 10

Column Names:
['id', 'created_at', 'title', 'company', 'source_url', 'description_raw', 'experience_years', 'published_at', 'location', 'experience_level']

First 5 Rows:

,id,created_at,title,company,source_url,description_raw,experience_years,published_at,location,experience_level
0,1,2026-03-19 00:00:00+00,Data Analyst,CRG,https://www.linkedin.com/jobs/view/data-analys...,Data Analyst\n\n\n\n\nDuration: 6-month contra...,3.0,NaN,NaN,NaN
1,2,2026-03-19 00:00:00+00,Data Analyst,Go Offer,https://www.linkedin.com/jobs/view/data-analys...,Join Go Offer as a Data Analyst with Russian l...,2.0,NaN,NaN,NaN
2,3,2026-03-19 00:00:00+00,Data Analyst (f/m/d),ITRex Group,https://pl.linkedin.com/jobs/view/data-analyst...,About ITRex\n\nTHE PLACE\n\nITRex - AI pioneer...,4.0,NaN,NaN,NaN
3,4,2026-03-19 00:00:00+00,Data Analyst - Fully Remote,Haystack,https://uk.linkedin.com/jobs/view/data-analyst...,Data Analyst\n\nWe're working with a leading g...,0.0,NaN,NaN,NaN
4,5,2026-03-19 00:00:00+00,Data Analyst | Remote,Crossing Hurdles,https://uk.linkedin.com/jobs/view/data-analyst...,Position: Join Expert Network: Business Intell...,0.0,NaN,NaN,NaN

Missing Values:

id                    0
created_at            0
title                 0
company               0
source_url            0
description_raw     208
experience_years    321
published_at         16
location             25
experience_level     16
dtype: int64

================================================================================
FILE: vacancy_skills_rows.csv
Rows: 13032
Columns: 2

Column Names:
['vacancy_id', 'skill_id']

First 5 Rows:

   vacancy_id  skill_id
0           1         1
1           1         2
2           1         3
3           1         4
4           1         5

Missing Values:

vacancy_id    0
skill_id      0
dtype: int64

In [4]:
from pathlib import Path
import pandas as pd

data_folder = Path("../data/raw")

skills = pd.read_csv(data_folder / "skills_rows.csv")
vacancies = pd.read_csv(data_folder / "vacancies_rows.csv")
vacancy_skills = pd.read_csv(data_folder / "vacancy_skills_rows.csv")

print("Skills:", skills.shape)
print("Vacancies:", vacancies.shape)
print("Vacancy-Skills:", vacancy_skills.shape)

Skills: (2033, 3)
Vacancies: (2154, 10)
Vacancy-Skills: (13032, 2)

In [5]:
print("SKILLS")
print(skills.dtypes)

print("\nVACANCIES")
print(vacancies.dtypes)

print("\nVACANCY SKILLS")
print(vacancy_skills.dtypes)

SKILLS
id            int64
created_at      str
name            str
dtype: object

VACANCIES
id                    int64
created_at              str
title                   str
company                 str
source_url              str
description_raw         str
experience_years    float64
published_at            str
location                str
experience_level        str
dtype: object

VACANCY SKILLS
vacancy_id    int64
skill_id      int64
dtype: object

In [6]:
pd.set_option('display.max_columns', None)

vacancies.head()

,id,created_at,title,company,source_url,description_raw,experience_years,published_at,location,experience_level
0,1,2026-03-19 00:00:00+00,Data Analyst,CRG,https://www.linkedin.com/jobs/view/data-analys...,Data Analyst\n\n\n\n\nDuration: 6-month contra...,3.0,NaN,NaN,NaN
1,2,2026-03-19 00:00:00+00,Data Analyst,Go Offer,https://www.linkedin.com/jobs/view/data-analys...,Join Go Offer as a Data Analyst with Russian l...,2.0,NaN,NaN,NaN
2,3,2026-03-19 00:00:00+00,Data Analyst (f/m/d),ITRex Group,https://pl.linkedin.com/jobs/view/data-analyst...,About ITRex\n\nTHE PLACE\n\nITRex - AI pioneer...,4.0,NaN,NaN,NaN
3,4,2026-03-19 00:00:00+00,Data Analyst - Fully Remote,Haystack,https://uk.linkedin.com/jobs/view/data-analyst...,Data Analyst\n\nWe're working with a leading g...,0.0,NaN,NaN,NaN
4,5,2026-03-19 00:00:00+00,Data Analyst | Remote,Crossing Hurdles,https://uk.linkedin.com/jobs/view/data-analyst...,Position: Join Expert Network: Business Intell...,0.0,NaN,NaN,NaN

In [7]:
print(vacancies.columns.tolist())

['id', 'created_at', 'title', 'company', 'source_url', 'description_raw', 'experience_years', 'published_at', 'location', 'experience_level']

In [8]:
print("Duplicate skills:", skills.duplicated().sum())

print("Duplicate vacancies:", vacancies.duplicated().sum())

print("Duplicate vacancy-skill mappings:", vacancy_skills.duplicated().sum())

Duplicate skills: 0
Duplicate vacancies: 0
Duplicate vacancy-skill mappings: 0

In [9]:
print("Number of unique job titles:", vacancies['title'].nunique())

vacancies['title'].value_counts().head(20)

Number of unique job titles: 1047

title
Data Analyst                648
Senior Data Analyst          91
Business Data Analyst        42
Junior Data Analyst          35
Data analyst                 21
Data Analyst II              20
Data Analyst Intern          17
Marketing Data Analyst       14
DATA ANALYST                 10
Healthcare Data Analyst      10
Data Analyst I               10
Data Analyst (m/w/d)          9
Remote Data Analyst Jobs      8
Sr. Data Analyst              8
Lead Data Analyst             8
Sr Data Analyst               7
Financial Data Analyst        7
HR Data Analyst               6
Data Analyst (Product)        5
Market Data Analyst           5
Name: count, dtype: int64

In [10]:
print("Number of unique companies:", vacancies['company'].nunique())

vacancies['company'].value_counts().head(20)

Number of unique companies: 1624

company
Unknown                                    100
Upwork                                      26
Insight Global                              18
Dice                                        13
Meta                                        13
EDWARD JONES                                11
AARATECH                                    10
Turing.com                                   9
Corporate                                    8
UnitedHealth Group                           8
Michael Page                                 8
Crossing Hurdles                             7
Kforce Inc                                   7
Brooksource                                  7
Revolut                                      6
Microsoft                                    6
Stripe                                       6
S&P Global                                   6
Get It Recruit - Information Technology      6
Emprego                                      6
Name: count, dtype: int64

In [11]:
vacancies['experience_years'].describe()

count    1833.000000
mean        1.409711
std         2.025938
min         0.000000
25%         0.000000
50%         0.000000
75%         2.000000
max        25.000000
Name: experience_years, dtype: float64

In [12]:
print("Unique locations:", vacancies['location'].nunique())

vacancies['location'].value_counts().head(20)

Unique locations: 777

location
Anywhere              167
United States         133
New York, NY           67
Kuala Lumpur           47
Singapore              32
San Francisco, CA      29
Austin, TX             24
India                  24
Paris, France          23
Los Angeles, CA        23
Chicago, IL            22
  United States        21
 Anywhere              20
United Kingdom         19
Washington, DC         19
Atlanta, GA            18
Petaling               17
Charlotte, NC          16
Tampa, FL              14
Canada                 13
Name: count, dtype: int64